### ISSUE TITLE
Error while parsing "queue:blocks" in worker

### ISSUE THREAD

**Issue by goodstemy** [kenigtech/keksplorer#10]
After starting agent and running worker I receive this message in console: 

> error: Error while parsing blocks: TypeError: undefined is not a function {}

**Comment by chebykin** [comment]
Does this error make worker do the work incorrectly? If not we can just ignore it since we building mvp now. The whole worker going to be rewritten after.

**Comment by chebykin** [comment]
What about `invalid` label? Is the issue invalid so we can close it?

**Comment by goodstemy** [comment]
Yeap. I think we can ignore that on mvp.
