### ISSUE TITLE
List of accounts

### ISSUE THREAD

**Issue by goodstemy** [kenigtech/keksplorer#15]
I'm not sure what I understand correctly how it works: `/api/accounts - list of all accounts seen in transactions`. After getting the request for current URL I grab all keys from redis by pattern `block_tx:*:*:list`. Redis return list of keys, that are matched for this wildcard. Each key have sorted list with accounts address, but addresses can be duplicated. I don't sure about correctness my actions.

**Comment by chebykin** [comment]
I agree with you that we have no such keys for accounts listing. Just ignore this api endpoint for now. I described my suggestions in #16

**Comment by chebykin** [comment]
Use `account:order` sorted set (member - account, score - block id).
Please, close if no more questions left.
