### ISSUE TITLE
Account details

### ISSUE THREAD

**Issue by goodstemy** [kenigtech/keksplorer#17]
Does worker implements account details and store with key: `account:0x000:detail`? I execute command `keys account:*:detail` and getting `(empty list or set)`.

**Comment by chebykin** [comment]
Account details key isn't implemented since there is no information to store. Serving txs list is enough.

**Comment by chebykin** [comment]
Why this issue is invalid?

**Comment by goodstemy** [comment]
Ok, so route `/api/accounts/#{account_id}` should be ignored until it's will be implemented? 
The changed issue to question.

**Comment by chebykin** [comment]
Yes, ignore it at all. We will add account balance getter as a proxy to parity later.
Just implement account transactions list: https://github.com/kenigtech/keksplorer/commit/df3eb09d656b289105af22cb23d7274c69089f5e

**Comment by goodstemy** [comment]
I will implement this in the next commit.

**Comment by chebykin** [comment]
@goodstemy Should we close it?

**Comment by goodstemy** [comment]
Yeap.
