### ISSUE TITLE
Env variables

### ISSUE THREAD

**Issue by goodstemy** [kenigtech/keksplorer#21]
We have REDIS_URL in .env file with value: `redis://127.0.0.1:6379/0`. But go-redis takes url like `127.0.0.1:6379`. Without schema and path. Should I create another variable in .env file like `GO_REDIS_URL`?

**Comment by chebykin** [comment]
Just use URL parser https://github.com/go-redis/redis/blob/master/options.go#L139

**Comment by goodstemy** [comment]
Cool, thanks.
