### ISSUE TITLE
Worker bug

### ISSUE THREAD

**Issue by goodstemy** [kenigtech/keksplorer#22]
After starting agent and redis I running worker. A worker grabs all blocks as well but later, when agent added new blocks worker don't see new blocks and don't set `1` to a number of the new blocks in `queue:block`. 

Logs showing this:

>error: Error while parsing blocks: TypeError: undefined is not a function {}
>info: Blocks to parse: 1 {}
>error: Error while parsing blocks: TypeError: undefined is not a function {}
>info: Blocks to parse: 1 {}
>error: Error while parsing blocks: TypeError: undefined is not a function {}
>...etc

Blocks to parse can vary from 1 to random number (as far I understand random number is remaining blocks in worker queue). 

@chebykin can you please try to repeat this bug on your workstation?

**Comment by chebykin** [comment]
thx, I will check this

**Comment by chebykin** [comment]
It seems like bug with the agent. No new blocks are added to the queue.
