### ISSUE TITLE
Specify version of project dependencies (golang, redis for example) in readme

### ISSUE THREAD

**Issue by Jonybang** [kenigtech/keksplorer#70]
Add to readme versions of project dependencies:
- golang
- redis
- etc

**Comment by Jonybang** [comment]
Problem on ubuntu 16 with installing golang 1.9 by gvm was solved:
https://github.com/moovweb/gvm/issues/221#issuecomment-343199219

**Comment by goodstemy** [comment]
Solved. https://github.com/kenigtech/keksplorer/pull/71

**Comment by Jonybang** [comment]
@goodstemy project works fine with go 1.9 version, i think you can change version in readme to 1.9

**Comment by goodstemy** [comment]
Yeap, but it also works great with 1.8+ versions
