### ISSUE TITLE
minimal web interface

### ISSUE THREAD

**Issue by chebykin** [kenigtech/keksplorer#8]
name folder `web`
provide web-service with at least one endpoint to unblock me from bulding docker-compose config

**Comment by goodstemy** [comment]
I think we can close this issue. I fix that in this commit: https://github.com/kenigtech/keksplorer/commit/188ba5f39deebe61c4e9cc97de2cfd19fd8c5441

In the next time, I will use the keywords in pr.

**Comment by chebykin** [comment]
ok
